# Generated by Django 4.2.2 on 2023-06-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_servicemetatags_blogmetatags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmetatags",
            name="blog",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta",
                to="services.blog",
            ),
        ),
    ]
