# Generated by Django 4.2.2 on 2023-06-24 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_blogmetatags_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicemetatags",
            name="service",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta",
                to="services.service",
            ),
        ),
    ]
