# Generated by Django 4.2.2 on 2023-06-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_alter_servicemetatags_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="title_quote",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
