# Generated by Django 4.2.2 on 2023-06-25 05:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_service_title_quote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
