# Generated by Django 4.2.2 on 2023-06-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_service_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.FileField(upload_to="codeverse/service"),
        ),
    ]
