# Generated by Django 4.2.2 on 2023-07-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0012_blogsection_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="meta_intro",
            field=models.TextField(null=True),
        ),
    ]
