# Generated by Django 4.2.2 on 2023-06-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_ourvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="ourvalue",
            name="order",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
