# Generated by Django 4.2.2 on 2023-06-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_ourvalue_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ourvalue",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
